name = "azraq27_julia"
uuid = "5a6b51c0-c7a4-440f-992f-b6d57cfe3d11"
repo = "https://github.com/azraq27/julia_registry"
description = "Random personal packages"

[packages]
a7949054-b901-59c6-b8e3-7238c29bf7f0 = { name = "MXNet", path = "M/MXNet" }
b9f58579-d931-4c4e-be85-8847ec00cbb6 = { name = "BIDSTools2", path = "B/BIDSTools2" }
f93e136e-b245-11e8-01f8-6da12d78f1e7 = { name = "AFNI", path = "A/AFNI" }
